### ISSUE TITLE
Error when using LOHA with colab

### ISSUE THREAD

**Issue by Dainsleiif** [KohakuBlueleaf/a1111-sd-webui-locon#10]
Error code that shows is
`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 151, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-locon/scripts/main.py", line 161, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_te_text_model_encoder_layers_0_mlp_fc1.hada_w1_a - must end in lora_up.weight, lora_down.weight or alpha`

Colab being used for reference is this one
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Locons work fine but Loha always gives this error. Any idea how to fix it?
Thank you for your time.

**Comment by KohakuBlueleaf** [comment]
Sorry for late response,
Can you check if your extension is on the latest version?
