### ISSUE TITLE
Every Lora failed with most recent version of stable-diffusion-webui

### ISSUE THREAD

**Issue by beebopkim** [KohakuBlueleaf/a1111-sd-webui-locon#15]
### Is there an existing issue for this?
It happened with most recent version of the stable-diffusion-webui, released just about 2 hours ago. So I guess there is no exsiting issue.

### What happened?
When I tried to use LoRA in txt2txt, the image generation pipeline was failed and dumped some python stack logs.

### Steps to reproduce the problem
I was able to reproduce with the clean install. So I write down here what I have done for the testing.

1. Git clone most recent version of stable-diffusion-webui; commit hash 4c1ad743e3baf1246db0711aa0107debf036a12b.
2. Install a1111-sd-webui-locon extension.
3. Put any checkpoint and LoRa in corresponding folders under models folder.
4. Run webui.sh script file.
5. Put any prompt words in txt2txt with lora and click the Generate button.

### What should have happened?
Should get a generated image using a LoRa.

### Commit where the problem happens
```
https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/commit/52c730a0d890755947344f6a4064837afe772946
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4c1ad743e3baf1246db0711aa0107debf036a12b
```

### What platforms do you use to access the UI ?
Apple Silicon M1 macos 22.3.0

### What browsers do you use to access the UI ?
Firefox

### Command Line Arguments
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate

### List of extensions
a1111-sd-webui-locon (enabled)

### Console logs
```
knut@Knuts-Mac-Studio sdwu-test % ./webui.sh           

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on knut user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.10 (main, Mar  1 2023, 22:32:25) [Clang 14.0.0 (clang-1400.0.29.202)]
Commit hash: 4c1ad743e3baf1246db0711aa0107debf036a12b
Installing requirements for Web UI
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Loading weights [6ce0161689] from /Users/knut/test/sdwu-test/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /Users/knut/test/sdwu-test/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0): 
Model loaded in 2.1s (load weights from disk: 0.2s, create model: 0.5s, apply weights to model: 0.5s, apply half(): 0.4s, move model to device: 0.5s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 4.5s (import torch: 0.7s, import gradio: 0.5s, import ldm: 0.2s, other imports: 0.4s, load scripts: 0.3s, load SD checkpoint: 2.1s, create ui: 0.2s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/gradio/routes.py", line 517, in join_queue
    if blocks.dependencies[event.fn_index].get("every", 0):
IndexError: list index out of range
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/gradio/routes.py", line 517, in join_queue
    if blocks.dependencies[event.fn_index].get("every", 0):
IndexError: list index out of range
Error completing request
Arguments: ('task(95lawgd0zft3kcw)', 'vladilena milize, lena,masterpiece, absurdres, highres, cinematic, 8k, intricate detail, ultra detailed, cinematic lighting, 1girl, pov, silver hair, (((light silver eyes))), white eyebrow, white eyelashes, looking at viewer, narrow waist, (large breast), (white thighhighs),  military uniform    <lora:90sAnimeAesthetic_v10:1>', 'EasyNegative  (((tattoo))), (((animal ears))), (((odd eyes))), (((nsfw))), bare chest', [], 20, 0, False, False, 1, 1, 7, 1816663567.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "/Users/knut/test/sdwu-test/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/knut/test/sdwu-test/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/knut/test/sdwu-test/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/knut/test/sdwu-test/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/Users/knut/test/sdwu-test/modules/processing.py", line 625, in process_images_inner
    uc = get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, p.steps, cached_uc)
  File "/Users/knut/test/sdwu-test/modules/processing.py", line 570, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "/Users/knut/test/sdwu-test/modules/prompt_parser.py", line 140, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "/Users/knut/test/sdwu-test/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/knut/test/sdwu-test/modules/sd_hijack_clip.py", line 229, in forward
    z = self.process_tokens(tokens, multipliers)
  File "/Users/knut/test/sdwu-test/modules/sd_hijack_clip.py", line 254, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "/Users/knut/test/sdwu-test/modules/sd_hijack_clip.py", line 302, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 811, in forward
    return self.text_model(
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 721, in forward
    encoder_outputs = self.encoder(
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 650, in forward
    layer_outputs = encoder_layer(
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 379, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 268, in forward
    query_states = self.q_proj(hidden_states) * self.scale
  File "/Users/knut/test/sdwu-test/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/knut/test/sdwu-test/extensions/a1111-sd-webui-locon/scripts/../../../extensions-builtin/Lora/lora.py", line 304, in lora_Linear_forward
    lora_apply_weights(self)
  File "/Users/knut/test/sdwu-test/extensions/a1111-sd-webui-locon/scripts/../../../extensions-builtin/Lora/lora.py", line 272, in lora_apply_weights
    self.weight += lora_calc_updown(lora, module, self.weight)
  File "/Users/knut/test/sdwu-test/extensions/a1111-sd-webui-locon/scripts/../../../extensions-builtin/Lora/lora.py", line 226, in lora_calc_updown
    down = module.down.weight.to(target.device, dtype=target.dtype)
AttributeError: 'function' object has no attribute 'weight'
```

Additional information
.

**Comment by xam0482** [comment]
unloading a1111-sd-webui-locon

**Comment by KohakuBlueleaf** [comment]
@beebopkim Already fix
