### ISSUE TITLE
error when using locon and lora together

### ISSUE THREAD

**Issue by wansf3** [KohakuBlueleaf/a1111-sd-webui-locon#2]
Error running process_batch: D:\stable-diffusion-webui\stable-diffusion-webuiLORA\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\stable-diffusion-webuiLORA\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\stable-diffusion-webui\stable-diffusion-webuiLORA\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 209, in process_batch
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight_tenc, weight_unet, text_encoder, unet)
  File "D:\stable-diffusion-webui\stable-diffusion-webuiLORA\extensions\a1111-sd-webui-locon\locon_compvis.py", line 62, in create_network_and_apply_compvis
    network = LoConNetworkCompvis(
  File "D:\stable-diffusion-webui\stable-diffusion-webuiLORA\extensions\a1111-sd-webui-locon\locon_compvis.py", line 289, in __init__
    self.text_encoder_loras, te_rep_modules = create_modules(
  File "D:\stable-diffusion-webui\stable-diffusion-webuiLORA\extensions\a1111-sd-webui-locon\locon_compvis.py", line 266, in create_modules
    alpha = comp_state_dict[f'{lora_name}.alpha'].item()
KeyError: 'lora_te_wrapped_transformer_text_model_encoder_layers_0_self_attn_k_proj.alpha'

it wont stop generation but completely ignore other loras ,

**Comment by KohakuBlueleaf** [comment]
Should be solved
Plz check

**Comment by wansf3** [comment]
fix confirmed , thanks!
