### ISSUE TITLE
Colab中使用时报错

### ISSUE THREAD

**Issue by AoyamaT1** [KohakuBlueleaf/a1111-sd-webui-locon#24]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7f723c0e7220>]: AssertionError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 170, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 141, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_te_text_model_encoder_layers_0_mlp_fc1.hada_w1_a - must end in lora_up.weight, lora_down.weight or alpha

**Comment by KohakuBlueleaf** [comment]
你沒有安裝插件喔
如果有安裝可能要重啟webui
