### ISSUE TITLE
getting RuntimeError: shape '[1280]' is invalid for input of size 0 while applying locon model

### ISSUE THREAD

**Issue by yeoyop** [KohakuBlueleaf/a1111-sd-webui-locon#28]
To create a public link, set `share=True` in `launch()`.
Startup time: 121.7s (import torch: 21.8s, import gradio: 3.5s, import ldm: 1.6s, other imports: 6.8s, setup codeformer: 0.6s, load scripts: 5.4s, load SD checkpoint: 77.1s, create ui: 4.1s, gradio launch: 0.7s).
locon load lora method
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001BA616390F0>]: RuntimeError
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\main.py", line 369, in load_lora
    sd = sd_models.read_state_dict(filename)
  File "D:\stable-diffusion-webui\modules\sd_models.py", line 241, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 101, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[1280]' is invalid for input of size 0

**Comment by KohakuBlueleaf** [comment]
@yeoyop Your safetensor file is broken 
This is not a issue for my extension so I will close this issue
I suggest you to put this issue and your file to safetensors' repo
