### ISSUE TITLE
The model might not be trained by sd-scripts error

### ISSUE THREAD

**Issue by SatyamSSJ10** [KohakuBlueleaf/a1111-sd-webui-locon#3]
`Error running process: G:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "G:\AI\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 206, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight_tenc, weight_unet, text_encoder, unet)
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 102, in create_network_and_apply_compvis
    state_dict = network.apply_lora_modules(du_state_dict)              # some weights are applied to text encoder
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 289, in apply_lora_modules
    state_dict = LoRANetworkCompvis.convert_state_dict_name_to_compvis(self.v2, du_state_dict)
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 193, in convert_state_dict_name_to_compvis
    compvis_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(v2, tokens[0])
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 182, in convert_diffusers_name_to_compvis
    assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
AssertionError: conversion failed: lora_unet_down_blocks_0_downsamplers_0_conv. the model may not be trained by `sd-scripts`.`

**Comment by KohakuBlueleaf** [comment]
This error should be solved by the newest extension
Plz check it

**Comment by SatyamSSJ10** [comment]
> This error should be solved by the newest extension
> Plz check it

Yea got it working. Btw when I train locon, does it train both lora and locon lora. Like does it train the green and yellow part? Or I have to merge lora and locon lora? If yes, how to merge?

**Comment by KohakuBlueleaf** [comment]
@SatyamSSJ10  Yes, by default you train both part.
