### ISSUE TITLE
Installed via Automatic1111 install from URL but getting error on LOCON

### ISSUE THREAD

**Issue by anonfaker24** [KohakuBlueleaf/a1111-sd-webui-locon#31]
Hello forgive me if this is a simple solution but I installed via automatic111 "install from url" and when I try and run  I get this error 

LoRA weight_unet: 1.5, weight_tenc: 1.5, model: kristenSchaal_v10(ca85f17f8f89)
dimension: {64, 32}, alpha: {64.0, 32.0}, multiplier_unet: 1.5, multiplier_tenc: 1.5
Error running process_batch: C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 356, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 243, in process_batch
    network, info = lora_compvis.create_network_and_apply_compvis(
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 149, in create_network_and_apply_compvis
    #   network_dim = 4
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 332, in __init__
    break
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 293, in convert_diffusers_name_to_compvis
    cv_name = (
AssertionError: conversion failed: lora_unet_time_embedding_linear_1. the model may not be trained by `sd-scripts`.

**Comment by KohakuBlueleaf** [comment]
@anonfaker24 This extension IS NOT FOR ADDITIONAL NETWORK
