### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Kaneda56** [KohakuBlueleaf/a1111-sd-webui-locon#36]
My locon is not is not applied and I have the following error :
```
loading Lora S:\test\stable-diffusion-webui\models\Lora\Style\huachong.ckpt: AttributeError
Traceback (most recent call last):
  File "S:\test\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 215, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "S:\test\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\main.py", line 289, in load_lora
    sd = sd_models.read_state_dict(filename)
  File "S:\test\stable-diffusion-webui\modules\sd_models.py", line 257, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "S:\test\stable-diffusion-webui\modules\sd_models.py", line 206, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'
```
python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  commit: [5ab7f213](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89)  •  checkpoint: [2c3bbd47cb](https://google.com/search?q=2c3bbd47cbb8b9e1a270ab547834f0abb082dd8b4bf5ef9a870f103ddae7f2fb)

**Comment by sledgehkg** [comment]
I'm getting similar:

locon load lora method
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x00000203A9EEE2C0>]: NameError
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\main.py", line 376, in load_lora
    for key_diffusers, weight in sd.items():
NameError: name 'sd' is not defined

I've tried reverting to an earlier version, but it makes no difference.

Can anybody help?

**Comment by neokiker** [comment]
@sledgehkg I have the same issue like you, when I go to locon page and read _"This extension is basically deprecated and will not have any official update at all."_

 I decided to delete locon extension. Now everything works again. 

Hope this help resolve your problem.
