### ISSUE TITLE
'LatentDiffusion' object has no attribute 'lora_layer_mapping' after today git pull stable-diffusion-webui

### ISSUE THREAD

**Issue by neskweek** [KohakuBlueleaf/a1111-sd-webui-locon#38]
Hello 
after regular git pull I now get, on each generation :   

```
Traceback (most recent call last):
  File "E:\SD\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 218, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "E:\SD\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\main.py", line 370, in load_lora
    is_sd2 = 'model_transformer_resblocks' in shared.sd_model.lora_layer_mapping
  File "E:\SD\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'lora_layer_mapping' 
```
running on windows 11 with RTX 3080
COMMANDLINE_ARGS= --xformers --listen

**Comment by neskweek** [comment]
well never mind, 
I : 
- deleted my venv folder
- removed the --listen argument 
- restarted the webui-user.bat 
now it works OK

**Comment by rangedreign** [comment]
I also get this error, running on windows 10 with gtx 1660 ti.
COMMANDLINE_ARGS= --theme dark --autolaunch --precision full --no-half --no-half-vae --medvram --disable-safe-unpickle --reinstall-torch --xformers --always-batch-cond-uncond

**Comment by hoodady** [comment]
loading Lora Z:\sd\stable-diffusion-webui\models\Lora\locon_angelina_v1_from_v3_64_32.safetensors: AssertionError ?it/s]
Traceback (most recent call last):
  File "Z:\sd\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 222, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "Z:\sd\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 192, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_unet_down_blocks_0_downsamplers_0_conv.lora_mid.weight - must end in lora_up.w


I get this random error? whats going on?

**Comment by Kadah** [comment]
The extension seems to be broken in a few ways with upstream A1111 changes, though I haven't gotten any of them except the following one.

Another breaking change in dev is https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/39ec4f06ffb2c26e1298b2c5d80874dc3fd693ac, which I've made a RP for: https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/pull/39

**Comment by duhast123** [comment]
the previous version
scripts\main.py
Add these lines:

**def assign_lora_names_to_compvis_modules(sd_model):
    lora_layer_mapping = {}

    for name, module in shared.sd_model.cond_stage_model.wrapped.named_modules():
        lora_name = name.replace(".", "_")
        lora_layer_mapping[lora_name] = module
        module.lora_layer_name = lora_name

    for name, module in shared.sd_model.model.named_modules():
        lora_name = name.replace(".", "_")
        lora_layer_mapping[lora_name] = module
        module.lora_layer_name = lora_name

    sd_model.lora_layer_mapping = lora_layer_mapping**

def load_lora(name, filename):
    print('locon load lora method')
    lora = LoraModule(name)
    lora.mtime = os.path.getmtime(filename)

    sd = sd_models.read_state_dict(filename)
	
    **if not hasattr(shared.sd_model, 'lora_layer_mapping'):
        assign_lora_names_to_compvis_modules(shared.sd_model)**

**Comment by NoppaiKohai** [comment]
I'm getting this error too, anyone figure out how to fix it

**Comment by aetherwu** [comment]
> the previous version scripts\main.py Add these lines:
> 
> **def assign_lora_names_to_compvis_modules(sd_model): lora_layer_mapping = {}
> 
> ```
> for name, module in shared.sd_model.cond_stage_model.wrapped.named_modules():
>     lora_name = name.replace(".", "_")
>     lora_layer_mapping[lora_name] = module
>     module.lora_layer_name = lora_name
> 
> for name, module in shared.sd_model.model.named_modules():
>     lora_name = name.replace(".", "_")
>     lora_layer_mapping[lora_name] = module
>     module.lora_layer_name = lora_name
> 
> sd_model.lora_layer_mapping = lora_layer_mapping**
> ```
> 
> def load_lora(name, filename): print('locon load lora method') lora = LoraModule(name) lora.mtime = os.path.getmtime(filename)
> 
> ```
> sd = sd_models.read_state_dict(filename)
> 
> **if not hasattr(shared.sd_model, 'lora_layer_mapping'):
>     assign_lora_names_to_compvis_modules(shared.sd_model)**
> ```

It works for me.
Let me clear the code for others:

Replace line 374 (or 370)
> is_sd2 = 'model_transformer_resblocks' in shared.sd_model.lora_layer_mapping

as

```
def assign_lora_names_to_compvis_modules(sd_model):
    lora_layer_mapping = {}

    for name, module in shared.sd_model.cond_stage_model.wrapped.named_modules():
        lora_name = name.replace(".", "_")
        lora_layer_mapping[lora_name] = module
        module.lora_layer_name = lora_name

    for name, module in shared.sd_model.model.named_modules():
        lora_name = name.replace(".", "_")
        lora_layer_mapping[lora_name] = module
        module.lora_layer_name = lora_name

    sd_model.lora_layer_mapping = lora_layer_mapping

def load_lora(name, filename):
    print('locon load lora method')
    lora = LoraModule(name)
    lora.mtime = os.path.getmtime(filename)

    sd = sd_models.read_state_dict(filename)

def load_lora(name, lora_on_disk):
    print('locon load lora method')
    lora = LoraModule(name, lora_on_disk)
    lora.mtime = os.path.getmtime(lora_on_disk.filename)

    sd = sd_models.read_state_dict(lora_on_disk.filename)

    if not hasattr(shared.sd_model, 'lora_layer_mapping'):
        assign_lora_names_to_compvis_modules(shared.sd_model)
        
    is_sd2 = True
```

Although it prints tons of extra logs.
Do @duhast123 know that how to turn it off?

**Comment by aetherwu** [comment]
> def load_lora(name, filename):
> def load_lora(name, lora_on_disk):

I looked at the code then realized that there were two 'load_lora' funcs?
