### ISSUE TITLE
locon is not working with google colab…

### ISSUE THREAD

**Issue by kemomimi2929** [KohakuBlueleaf/a1111-sd-webui-locon#44]
In a recent update
I cannot use locon in google colab.
I am having a hard time.
Does anyone know of a code that works with colab?

**Comment by DEX-1101** [comment]
`!cd /content/stable-diffusion-webui/extensions/a1111-sd-webui-locon && git checkout 04b768b`
run it after cloning webui, work for me so far

**Comment by kemomimi2929** [comment]
thank you！
I used the code you gave me
I got this error.
Anyone know the cause?
"loading Lora /content/stable-diffusion-webui/models/Lora/happymeek_loha.safetensors: AssertionError
Traceback (most recent call last):
   File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 253, in load_loras
     lora = load_lora(name, lora_on_disk)
   File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 220, in load_lora
     raise AssertionError(f"Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha")
AssertionError: Bad Lora layer name: lora_te_text_model_encoder_layers_0_mlp_fc1.hada_w1_a - must end in lora_up.weight, lora_down.weight or alpha"

It's this error.
please. Help me.

**Comment by DEX-1101** [comment]
if you're using latests webui, you can try using old commit to make it work since this extension is deprecated, or you can try https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris instead, idk if its works on normal lora since its lycoris type.

**Comment by KohakuBlueleaf** [comment]
@DEX-1101 lycoris ext can support "normal lora"
Since "normal lora" is subset of locon

**Comment by AmndaIC1805** [comment]
hello anyone know what causing this error ?
reading lora /content/bilek/models/LyCORIS/victoricamajonotabitabi.safetensors: AssertionError
Traceback (most recent call last):
  File "/content/bilek/extensions/bilek-lycoris/lycoris.py", line 146, in __init__
    self.metadata = sd_models.read_metadata_from_safetensors(filename)
  File "/content/bilek/modules/sd_models.py", line 232, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: /content/bilek/models/LyCORIS/victoricamajonotabitabi.safetensors is not a safetensors file

**Comment by DEX-1101** [comment]
where your download the file? 
its either wrong extension or corrupted download/uncompleted.

**Comment by AmndaIC1805** [comment]
> where your download the file? its either wrong extension or corrupted download/uncompleted.

thanks for your reply, i just figure out that was corrupted of uncomplete download because civitai server is kinda meh, ive been try to redownload it and it been works.
