### ISSUE TITLE
Locon doesn't work...?

### ISSUE THREAD

**Issue by YarivTawili** [KohakuBlueleaf/a1111-sd-webui-locon#48]
Starting today I see this error on every locon I have: 

locon load lora method
loading Lora D:\Stable-diffusion\stable-diffusion-portable-main\models\Lora\Porn\Touch&Pose\pantypullPantydropV1.safetensors: AttributeError
Traceback (most recent call last):
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 253, in load_loras
    lora = load_lora(name, lora_on_disk)
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\a1111-sd-webui-locon\scripts\main.py", line 374, in load_lora
    is_sd2 = 'model_transformer_resblocks' in shared.sd_model.lora_layer_mapping
  File "D:\Stable-diffusion\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'lora_layer_mapping'

From the other hand, I'm getting an error for lora's as well (no locon used here):

locon load lora method
loading Lora D:\Stable-diffusion\stable-diffusion-portable-main\models\Lora\Lib\Celeb\galGadotLora_v10.safetensors: AttributeError
Traceback (most recent call last):
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 253, in load_loras
    lora = load_lora(name, lora_on_disk)
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\a1111-sd-webui-locon\scripts\main.py", line 374, in load_lora
    is_sd2 = 'model_transformer_resblocks' in shared.sd_model.lora_layer_mapping
  File "D:\Stable-diffusion\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'lora_layer_mapping'

So I'm not sure who is responsible for it.

**Comment by KohakuBlueleaf** [comment]
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/assets/59680068/c66dc209-5dbc-4c63-951e-055ba61ba5d7)
