### ISSUE TITLE
AttributeError: 'function' object has no attribute 'weight'

### ISSUE THREAD

**Issue by slashedstar** [KohakuBlueleaf/a1111-sd-webui-locon#5]
It seems to happen with all non-locon loras, the locon works fine, regular loras work fine when used in the additional networks extension, this only happens when using then in the prompt like ```<lora:name:1>``` 

`Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 621, in process_images_inner
    uc = get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, p.steps, cached_uc)
  File "F:\stable-diffusion-webui\modules\processing.py", line 570, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "F:\stable-diffusion-webui\modules\prompt_parser.py", line 140, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "F:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 229, in forward
    z = self.process_tokens(tokens, multipliers)
  File "F:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 254, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "F:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 302, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
    return self.text_model(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 721, in forward
    encoder_outputs = self.encoder(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 650, in forward
    layer_outputs = encoder_layer(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 379, in forward
    hidden_states, attn_weights = self.self_attn(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 268, in forward
    query_states = self.q_proj(hidden_states) * self.scale
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "F:\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\main.py", line 348, in lora_forward
    scale = lora_m.multiplier * (module.alpha / module.down.weight.size(0) if module.alpha else 1.0)
AttributeError: 'function' object has no attribute 'weight'`

With the lora block weight extension it still outputs 
`File "F:\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\main.py", line 350, in lora_forward
    scale = lora_m.multiplier * (module.alpha / module.dim if module.alpha else 1.0)
AttributeError: 'LoraUpDownModule' object has no attribute 'dim'`

**Comment by KohakuBlueleaf** [comment]
Will check it

**Comment by slashedstar** [comment]
Thanks, also, it outputs in the console `Additional Network extension not installed, Only hijack built-in lora` despite the extension is being installed, it may be related
![image](https://user-images.githubusercontent.com/103432664/224394505-99c43ca7-8790-4f24-946a-9fc2eba1d5b5.png)

**Comment by goticzuk** [comment]
The same error started to appear for me yesterday.
<img width="925" alt="image" src="https://user-images.githubusercontent.com/94347089/224397821-e823bcfe-7e1b-4598-a5f1-483fc79e9498.png">

**Comment by ruSauron** [comment]
Same issue since last update. Previous one are fine

For other users, not devs:
you can rollback to working version by opening cmd in
`_Path_to_\stable-diffusion-webui-master\extensions\a1111-sd-webui-locon`

after that execute command:
`git reset --hard 31a1e215201ecb4ca577e4cf50132133338bcf96`

**Comment by KohakuBlueleaf** [comment]
@slashedstar If your addnet ext does not use the default name (sd-webui-additional-networks)
the extension cannot identify it correctly

**Comment by KohakuBlueleaf** [comment]
@ruSauron @goticzuk @slashedstar 
This problem should be fixed
please check new update and report if there is another issue

**Comment by sotokisehiro** [comment]
After fixing the code it works fine.
thank you! 😊

**Comment by slashedstar** [comment]
> @slashedstar If your addnet ext does not use the default name (sd-webui-additional-networks) the extension cannot identify it correctly
I think the name is correct:
![image](https://user-images.githubusercontent.com/103432664/224458556-4d102c1b-545b-4675-8a25-5aa58ac8ec33.png)
Either way, both errors were solved, nice work 👍
